FROM python:3.10-alpine as builder

RUN mkdir /opt/venv
RUN apk add --no-cache build-base gcc gfortran openblas-dev linux-headers \
    && python3 -m venv /opt/venv \
    && /opt/venv/bin/python3 -m pip install flask

COPY reqs.txt .
RUN /opt/venv/bin/python3 -m pip install -r reqs.txt

FROM python:3.10-alpine as prod

COPY --from=builder /opt/venv /opt/venv

WORKDIR /app
COPY *.py ./


ENTRYPOINT [ "/opt/venv/bin/python3", "./server.py" ]
