- hosts: workers
  vars:
    expected: "Connection failure: [Errno 104] Connection reset by peer"
    host_group: "{{ groups['workers'] }}"
    assigned_port: "{{ (worker.port | int + host_group.index(inventory_hostname)) }}"
    bin_dir: "/tmp/iluvatar/bin"
    exe_dest: "{{bin_dir}}/{{ worker.bin_name }}"
    config_dest: "{{bin_dir}}/{{ inventory_hostname }}.json"
    __architecture: "{{ servers[ansible_host].architecture | default('x86_64-unknown-linux-gnu') }}"
    def_bin_src: "{{iluvatar_home}}/target/{{__architecture}}/{{target}}"
    __bin_src: "{{ worker_bin_src | default(def_bin_src) }}"
    __remote_bin_src: "{{ remote_bin_src | default(false) }}"
    __worker_address: "{{ worker_address | default(servers[ansible_host].internal_ip) }}"
    __hardware_interface: "{{ hardware_interface | default(servers[ansible_host].hardware_interface) }}"
    SIGINT: 2
    coded_proxy_env:
      "ILUVATAR_WORKER__name": "{{ inventory_hostname }}"
      "ILUVATAR_WORKER__port": "{{ assigned_port }}"
      "ILUVATAR_WORKER__address" : "{{ __worker_address }}"
      "ILUVATAR_WORKER__logging__basename": "worker_{{ inventory_hostname }}"
      "ILUVATAR_WORKER__logging__directory": "{{ worker_log_dir | default('/tmp/iluvatar/logs') }}"
      "ILUVATAR_WORKER__logging__level": "{{ worker_log_level | default('info') }}"
      "ILUVATAR_WORKER__load_balancer_url" : "http://{{ controller.host }}:{{ controller.port }}"
      "ILUVATAR_WORKER__timeout_sec" : "{{ worker_timeout_sec | default(6000) }}"
      "ILUVATAR_WORKER__tokio_event_interval" : "{{ worker_tokio_event_interval | default(20) }}"
      "ILUVATAR_WORKER__tokio_queue_interval" : "{{ worker_tokio_queue_interval | default(20) }}"
      # Limits
      "ILUVATAR_WORKER__limits__mem_max_mb" : "{{ worker_mem_max | default(5000) }}"

      # Container resources
      "ILUVATAR_WORKER__container_resources__memory_mb" : "{{ worker_memory_mb | default(2048) }}"
      "ILUVATAR_WORKER__container_resources__eviction" : "{{ worker_eviction | default('LRU') }}"
      "ILUVATAR_WORKER__container_resources__startup_timeout_ms" : "{{ worker_startup_timeout_ms | default(10000) }}"
      "ILUVATAR_WORKER__container_resources__pool_freq_ms" : "{{ worker_cm_pool_freq_ms | default(1000) }}"
      "ILUVATAR_WORKER__container_resources__concurrent_creation" : "{{ worker_concurrent_creation | default(5) }}"
      "ILUVATAR_WORKER__container_resources__memory_buffer_mb" : "{{ worker_memory_buffer | default(0) }}"
      "ILUVATAR_WORKER__container_resources__snapshotter" : "{{ worker_snapshotter | default('zfs') }}"
      "ILUVATAR_WORKER__container_resources__cpu_resource__count" : "{{ worker_cores | default(4) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__count" : "{{ worker_gpus | default(0) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__is_tegra" : "{{ worker_is_tegra | default(false) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__use_standalone_mps" : "{{ standalone_mps | default(false) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__per_func_memory_mb" : "{{ per_func_memory_mb | default(2048) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__mps_limit_active_threads" : "{{ mps_limit_threads | default(false) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__use_driver_hook" : "{{ use_driver_hook | default(false) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__funcs_per_device" : "{{ funcs_per_device | default(0) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__limit_on_utilization" : "{{ gpu_limit_on_utilization | default(0) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__concurrent_running_funcs" : "{{ gpu_concurrent_running | default(0) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__prefetch_memory" : "{{ gpu_prefetch_memory | default(false) }}"
      "ILUVATAR_WORKER__container_resources__gpu_resource__status_update_freq_ms" : "{{ gpu_status_update | default(0) }}"

      # Networking
      "ILUVATAR_WORKER__networking__pool_size" : "{{ worker_pool_size | default(10) }}"
      "ILUVATAR_WORKER__networking__use_pool" : "{{ worker_use_pool | default(true) }}"
      "ILUVATAR_WORKER__networking__pool_freq_ms" : "{{ worker_net_pool_freq_ms | default(1000) }}"
      "ILUVATAR_WORKER__networking__hardware_interface" : "{{ __hardware_interface }}"
      # Energy config
      "ILUVATAR_WORKER__energy__rapl_freq_ms" : "{{ worker_rapl_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__perf_freq_ms" : "{{ worker_perf_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__tegra_freq_ms" : "{{ worker_tegra_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__process_freq_ms" : "{{ worker_process_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__kernel_cpu_frequencies_freq_ms" : "{{ worker_kernel_cpu_frequencies_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__hardware_cpu_frequencies_freq_ms" : "{{ worker_hardware_cpu_frequencies_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__ipmi_freq_ms" : "{{ worker_ipmi_log_freq_ms | default(0) }}"
      "ILUVATAR_WORKER__energy__ipmi_pass_file" : "{{ worker_ipmi_pass_file | default('') }}"
      "ILUVATAR_WORKER__energy__ipmi_ip_addr" : "{{ worker_ipmi_ip_addr | default(servers[ansible_host].ipmi_ip) }}"
      "ILUVATAR_WORKER__energy__log_folder": "{{ worker_log_dir | default('/tmp/iluvatar/logs') }}"
      # Energy cap config
      "ILUVATAR_WORKER__energy_cap__power_cap" : "{{ worker_power_cap | default(0.0) }}"
      "ILUVATAR_WORKER__energy_cap__power_cap_version" : "{{ worker_power_cap_version | default('V0') }}"

      # Influx config
      "ILUVATAR_WORKER__influx__host" : "{{ influx.address }}"
      "ILUVATAR_WORKER__influx__org" : "{{ influx.organization }}"
      "ILUVATAR_WORKER__influx__token" : "{{ hostvars[ groups['influx']|first ].influx_token | default('') }}"
      "ILUVATAR_WORKER__influx__enabled" : "{{ influx.enabled }}"
      "ILUVATAR_WORKER__influx__update_freq_ms" : "{{ influx.update_freq_ms }}"
      # Invocation config
      "ILUVATAR_WORKER__invocation__retries" : "{{ worker_invoke_retries | default(0) }}"
      "ILUVATAR_WORKER__invocation__queue_sleep_ms" : "{{ worker_queue_sleep_ms | default(100) }}"
      "ILUVATAR_WORKER__invocation__queue_policies__cpu" : "{{ worker_cpu_queue_policy | default('fcfs') }}"
      "ILUVATAR_WORKER__invocation__queue_policies__gpu" : "{{ worker_gpu_queue_policy | default('mqfq_select_out_len') }}"
      "ILUVATAR_WORKER__invocation__queues__gpu" : "{{ worker_gpu_queue | default('mqfq') }}"
      "ILUVATAR_WORKER__invocation__queues__cpu" : "{{ worker_cpu_queue | default('serial') }}"
      "ILUVATAR_WORKER__invocation__enqueueing_policy" : "{{ worker_enqueueing | default('All') }}"
      # Status config
      "ILUVATAR_WORKER__status__report_freq_ms" : "{{ worker_status_ms | default(2000) }}"
      # MQFQ Config
      "ILUVATAR_WORKER__invocation__mqfq_config__allowed_overrun" : "{{ mqfq_allowed_overrun | default(0.0) }}"
      "ILUVATAR_WORKER__invocation__mqfq_config__in_flight" : "{{ mqfq_in_flight | default(false) }}"
      "ILUVATAR_WORKER__invocation__mqfq_config__dynamic_weights" : "{{ mqfq_dynamic_weights | default(false) }}"
      "ILUVATAR_WORKER__invocation__mqfq_config__service_average" : "{{ mqfq_service_average | default(10.0) }}"
      "ILUVATAR_WORKER__invocation__mqfq_config__ttl_sec" : "{{ mqfq_ttl_sec | default(2.0) }}"
      "ILUVATAR_WORKER__invocation__mqfq_config__weight_logging_ms" : "{{ mqfq_weight_logging_ms | default(0) }}"
      "ILUVATAR_WORKER__invocation__mqfq_config__flow_select_cnt" : "{{ mqfq_flow_select_cnt | default(0) }}"
    proxy_env: "{{ coded_proxy_env | combine(worker.environment, recursive=True) }}"

  vars_files:
    - group_vars/all.yml
    - group_vars/host_addresses.yml

  tasks:
  - name: Create bin directory
    file:
      path: "{{bin_dir}}"
      state: directory
      recurse: yes
    become: yes
      
  - name: copy worker executable
    ansible.builtin.copy:
      src: "{{__bin_src}}/{{worker.bin_name}}"
      dest: "{{exe_dest}}"
      mode: "preserve"
      remote_src: "{{__remote_bin_src}}"
    become: yes

  - name: copy worker config
    ansible.builtin.copy:
      src: "{{iluvatar_home}}/target/{{target}}/{{worker.config_name}}"
      dest: "{{config_dest}}"
      mode: "preserve"
    become: yes

  - name: Get running worker process
    shell: "ps -ef | grep -v grep | grep -w {{ worker.bin_name }} | awk '{print $2}'"
    register: running_worker
    when: mode == "clean"

  - name: Kill running worker process on localhost
    shell: "kill -s INT {{ item }}"
    with_items: "{{ running_worker.stdout_lines }}"
    become: yes
    when: (ansible_host == "127.0.0.1" or ansible_host == "localhost") and mode == "clean"
    run_once: true

  - name: Kill running worker process distrib
    shell: "kill -s INT {{ item }}"
    when: (ansible_host != "127.0.0.1" and ansible_host != "localhost") and mode == "clean"
    with_items: "{{ running_worker.stdout_lines }}"
    become: yes

  - name: clean localhost
    ansible.builtin.command: 
      argv: 
        - "{{exe_dest}}"
        - -c 
        - "{{config_dest}}"
        - clean
    become: yes
    when: (ansible_host == "127.0.0.1" or ansible_host == "localhost") and mode == "clean"
    run_once: true
    register: clean_cmd
    failed_when: clean_cmd.rc != 0
    environment: "{{proxy_env}}"

  - name: clean distrib host
    ansible.builtin.command: 
      argv: 
        - "{{exe_dest}}"
        - -c 
        - "{{config_dest}}"
        - clean
    become: yes
    when: mode == "clean"
    register: clean_cmd
    failed_when: clean_cmd.rc != 0
    environment: "{{proxy_env}}"

  - name: run worker executable
    ansible.builtin.command: 
      argv: 
        - "{{exe_dest}}"
        - -c 
        - "{{config_dest}}"
    become: yes
    async: 2592000               # 60*60*24*30 – 1 month
    poll: 0
    when: mode == "deploy"
    environment: "{{proxy_env}}"
    register: worker_output

  - name: run worker executable through perf
    ansible.builtin.command: 
      argv: 
        - perf
        - record
        - -F
        - "{{perf_record_freq_hz}} | default(1000)"
        - -g
        - --user-callchains
        - --inherit
        - -o 
        - "{{worker_log_dir}}/perf.data"
        - "{{exe_dest}}"
        - -c 
        - "{{config_dest}}"
    become: yes
    async: 2592000               # 60*60*24*30 – 1 month
    poll: 0
    when: mode == "perf"
    environment: "{{proxy_env}}"
    register: worker_output

  - name: debug print
    # when: ansible_host == "127.0.0.1" or ansible_host == "localhost"
    # run_once: true
    debug:
      msg: "{{ worker_output }}"

  - name: wait until the worker on this host is up and running
    ansible.builtin.uri:
      url:
        "http://{{__worker_address}}:{{assigned_port}}/ping"
      validate_certs: "no"
      # RPC server doesn't accept basic HTTP connections
      # but we can try connecting to it once it's up and know it's alive
      status_code: [-1] #[-1, 0.9, 1.1]
    register: result
    until: result.msg == expected
    retries: 10
    delay: 5
    when: mode == "deploy" or mode == "perf"
