use clap::{ArgMatches, App, Arg, SubCommand};

pub fn parse() -> ArgMatches<'static> {
  App::new("ilúvatar_energy_mon")
    .version("0.1.0")
    .about("Ilúvatar Energy Monitor")
    .subcommand(SubCommand::with_name("analyze")
      .arg(Arg::with_name("logfile")
        .long("logfile")
        .help("Path to the Ilúvatar log file to consume")
        .required(true)
        .takes_value(true))
      .arg(Arg::with_name("energy-folder")
        .long("energy-folder")
        .help("Path to the folder energy consumption was stored in")
        .required(true)
        .takes_value(true)))
    .subcommand(SubCommand::with_name("monitor")
      .arg(Arg::with_name("outdir")
        .long("outdir")
        .help("Folder to store energy results in")
        .required(true)
        .takes_value(true))
      .arg(Arg::with_name("poll")
        .short("p")
        .long("poll")
        .help("The period in seconds between each poll")
        .required(false)
        .default_value("20")
        .takes_value(true)))
    .get_matches()
}
