disallowed-methods = [
    # fully qualified function/method name:
    "tokio::time::Instant::now",
    "tokio::spawn",
    "std::thread::spawn",
    "std::time::Instant::now",
    "time::OffsetDateTime::now_utc",
    { path = "time::OffsetDateTime::now_local", allow-invalid = true },
]

disallowed-types = [
    # fully qualified function/method name:
    "std::time::Instant",
    "std::time::SystemTime",
    "std::thread::Builder"
]