ansible ansible_connection=local

[workers]
worker1     ansible_host=v-gpu3.victor.futuresystems.org    ansible_connection=ssh

[controller]
controller1     ansible_host=v-gpu3.victor.futuresystems.org    ansible_connection=ssh

[influx]
influx1     ansible_host=v-gpu3.victor.futuresystems.org    ansible_connection=ssh
