ansible ansible_connection=local

[workers]
worker1     ansible_host=d7525-10s10327.wisc.cloudlab.us    ansible_connection=ssh

[controller]
controller1     ansible_host=d7525-10s10327.wisc.cloudlab.us    ansible_connection=ssh

[influx]
influx1     ansible_host=d7525-10s10327.wisc.cloudlab.us    ansible_connection=ssh
