* On Victor 
** Ipmi (BMC) 
This is, most likely, the actual power consumption of the entire server. 
Output of =dcmi power reading= is something like

    Instantaneous power reading:                    75 Watts
    Minimum during sampling period:                 68 Watts
    Maximum during sampling period:                444 Watts
    Average power reading over sample period:      101 Watts
    IPMI timestamp:                           Thu Jul  7 20:50:47 2022
    Sampling period:                          00425664 Seconds.
    Power reading state is:                   activated

** RAPL 
- Driver still not found. Need to upgrade kernel? 
- RAPL is a software power meter and uses a model based on CPU freq and voltage. 
- turbostat --debug provides CPU and RAM Watts. CPU is ~40 and RAM is ~5, but fluctuates quite a bit, why!?  
- rapl-read https://web.eece.maine.edu/~vweaver/projects/rapl/index.html works. 
- Fails for powercap, but reading the msrs works (hence needs root). Kernel driver issue??
- on v-019:/home/prateeks/rapl-read will output:
        Sleeping 1 second

        Package 0:
                Package energy: 20.273865J
                PowerPlane0 (cores): 0.000000J
                DRAM: 1.299484J
        Package 1:
                Package energy: 18.747803J
                PowerPlane0 (cores): 0.000000J
                DRAM: 0.902191J




* AMD  Desktop
- We dont have full-system true power
  - Buy a separate power meter? 
- AMDuProf for software power meter. Installs easily on ubuntu.
- Shows CPU/package power (~5 W idle, matching specs), GPU power (50W lol)

* Powertop
- https://github.com/fenrus75/powertop/blob/master/src/process/powerconsumer.cpp
- How does it work? Just CPU-time * energy? for per-process accounting? 

* PowerAPI
- https://powerapi-ng.github.io/introduction.html
- software power meters 

* PAPI RAPL
- Annotate program 
- Class project? Not relevant but uses rapl in rust https://github.com/cs-21-pt-9-01/rapl.rs 


