[package]
name = "iluvatar_library"
description = "Generic code not specific to any piece of the platform."
version.workspace = true
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.13"
guid-create = "0.2.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
time = { version = "0.3", features = [ "formatting" ] }
tzdb = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "tracing-log", "parking_lot", "env-filter"] }
tracing-appender = "0.2.2"
tracing-flame="0.2"
pin-project = "1"
dashmap = "5.3.4"
parking_lot = "0.12.1"
tokio = { version = "1.19", features = ["macros", "rt-multi-thread", "test-util", "sync", "parking_lot", "signal"] }
ordered-float = "3.4.0"
bitflags = "1.3"
influxdb2 = "0.4"
num-traits = "0.2"
influxdb2-structmap = "0.2"

[dev-dependencies]
rstest = "0.13.0"
float-cmp = "0.9.0"
nix = "0.26"

[features]
full_spans = []
