FROM nvcr.io/nvidia/tensorrt:21.12-py3

RUN ln -s /usr/lib/x86_64-linux-gnu/libnvinfer.so.8 /usr/lib/x86_64-linux-gnu/libnvinfer.so.7 && \
  ln -s /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.8 /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.7 && \
   python3 -m pip install flask gunicorn
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/"

WORKDIR /app
COPY reqs.txt .
RUN python3 -m pip install -r reqs.txt

COPY *.py ./

ENTRYPOINT [ "gunicorn", "-w", "1", "server:app" ]
