FROM python:3.10-slim-bullseye

# TODO: these images are really big...
# Do something to slim them down

# TODO: test all functions, some will probably need weird things like the video and cnn

RUN apt-get update -y && apt-get upgrade -y && python3 -m pip install --upgrade pip && python3 -m pip install flask

WORKDIR /app
COPY *.py ./
COPY reqs.txt .

RUN python3 -m pip install -r reqs.txt

ENTRYPOINT [ "python3", "./server.py" ]
