FROM nvidia/cuda:11.4.0-base-ubuntu20.04

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3 python3-pip && python3 -m pip install flask gunicorn && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY reqs.txt .
RUN python3 -m pip install -r reqs.txt

COPY *.py ./

ENTRYPOINT [ "gunicorn", "-w", "1", "server:app" ]
