FROM python:3.10-slim-bullseye

# TODO: these images are really big...
# Do something to slim them down

RUN apt-get update -y && apt-get upgrade -y && python3 -m pip install --upgrade pip && python3 -m pip install flask gunicorn

WORKDIR /app
COPY reqs.txt .
RUN python3 -m pip install -r reqs.txt

COPY *.py ./

# ENTRYPOINT [ "python3", "./server.py" ]
ENTRYPOINT [ "gunicorn", "-w", "1", "server:app" ]