FROM python:3.10-slim-bullseye

# TODO: these images are really big...
# Do something to slim them down

WORKDIR /app
COPY reqs.txt .
RUN python3 -m pip install --upgrade pip && python3 -m pip install flask gunicorn && python3 -m pip install -r reqs.txt && python3 -m pip cache purge

COPY *.py .

ENTRYPOINT [ "gunicorn", "-w", "1", "server:app" ]