FROM gromacs/gromacs:latest

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install flask gunicorn && \
    python3 -m pip install -r requirements.txt && \
    python3 -m pip cache purge && \
    rm -rf /var/lib/apt/lists/*


COPY *.py ./

ENTRYPOINT [ "gunicorn", "-w", "1", "server:app" ]
