iluvatar_home: "{{ lookup('env', 'ILU_HOME') | default(playbook_dir ~ '/..', true) }}"
mode: deploy
target: release
def_bin_src: "{{iluvatar_home}}/target/{{target}}"
__bin_src: "{{ bin_src | default(def_bin_src) }}"
__remote_bin_src: "{{ remote_bin_src | default(false) }}"

controller:
  bin_name: "iluvatar_controller"
  config_name: "controller.json"
  host: "{{ hostvars[ groups['controller']|first ].ansible_host }}"
  port: "{{ controller_port | default(8089) }}"
  algorithm: "{{ controller_algorithm | default('LeastLoaded') }}"
  load_metric: "{{ controller_load_metric | default('loadavg') }}"

worker:
  bin_name: "iluvatar_worker"
  config_name: "worker.json"
  port: "{{ worker_port | default(8070) }}"


__influx_api_port: 8086
influx:
  docker_image: influxdb:2.0.9
  container_name: "iluvatar_influx"
  api_port: "{{ __influx_api_port }}"
  address: "http://{{ hostvars[ groups['influx']|first ].ansible_host }}:{{ __influx_api_port }}"
  enabled: "{{ influx_enabled | default(true) }}"
  username: iluvatar
  password: iluvatar_password
  organization: iluvatar
  bucket: foobar
  retention: 3h
  update_freq_ms: "{{ influx_update_freq_ms | default(1000) }}"

