name: master.yml
on:
  push:
    branches:
      - master
jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: rustup component add clippy
      - run: make clippy

    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Docker
          uses: docker/setup-docker-action@v4

        - name: Set up Python 3.13
          uses: actions/setup-python@v5
          with:
            python-version: 3.13

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push images
          working-directory: src/load/functions/python3
          run: python3 build.py --repo cosinfaas --version latest